package com.tpmlogis.bssapp.model;

// Generated 2014. 3. 4 ?? 10:20:32 by Hibernate Tools 4.0.0

/**
 * OrderdetailsId generated by hbm2java
 */
public class OrderdetailsId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1450414323334763067L;
	private int ordernumber;
	private String productcode;

	public OrderdetailsId() {
	}

	public OrderdetailsId(int ordernumber, String productcode) {
		this.ordernumber = ordernumber;
		this.productcode = productcode;
	}

	public int getOrdernumber() {
		return this.ordernumber;
	}

	public void setOrdernumber(int ordernumber) {
		this.ordernumber = ordernumber;
	}

	public String getProductcode() {
		return this.productcode;
	}

	public void setProductcode(String productcode) {
		this.productcode = productcode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrderdetailsId))
			return false;
		OrderdetailsId castOther = (OrderdetailsId) other;

		return (this.getOrdernumber() == castOther.getOrdernumber())
				&& ((this.getProductcode() == castOther.getProductcode()) || (this.getProductcode() != null
						&& castOther.getProductcode() != null && this.getProductcode().equals(castOther.getProductcode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getOrdernumber();
		result = 37 * result + (getProductcode() == null ? 0 : this.getProductcode().hashCode());
		return result;
	}

}
