package com.tpmlogis.bssapp.model;

// Generated 2014. 3. 4 ?? 10:20:32 by Hibernate Tools 4.0.0

/**
 * PaymentsId generated by hbm2java
 */
public class PaymentsId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1183441057115221446L;
	private int customernumber;
	private String checknumber;

	public PaymentsId() {
	}

	public PaymentsId(int customernumber, String checknumber) {
		this.customernumber = customernumber;
		this.checknumber = checknumber;
	}

	public int getCustomernumber() {
		return this.customernumber;
	}

	public void setCustomernumber(int customernumber) {
		this.customernumber = customernumber;
	}

	public String getChecknumber() {
		return this.checknumber;
	}

	public void setChecknumber(String checknumber) {
		this.checknumber = checknumber;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PaymentsId))
			return false;
		PaymentsId castOther = (PaymentsId) other;

		return (this.getCustomernumber() == castOther.getCustomernumber())
				&& ((this.getChecknumber() == castOther.getChecknumber()) || (this.getChecknumber() != null
						&& castOther.getChecknumber() != null && this.getChecknumber().equals(castOther.getChecknumber())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCustomernumber();
		result = 37 * result + (getChecknumber() == null ? 0 : this.getChecknumber().hashCode());
		return result;
	}

}
