package com.tpmlogis.bssapp.model;

// Generated 2014. 3. 4 ?? 10:20:32 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Payments generated by hbm2java
 */
public class Payments implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5710106513949255782L;
	private PaymentsId id;
	private Integer version;
	private Customers customers;
	private Date paymentdate;
	private double amount;

	public Payments() {
	}

	public Payments(PaymentsId id, Customers customers, Date paymentdate, double amount) {
		this.id = id;
		this.customers = customers;
		this.paymentdate = paymentdate;
		this.amount = amount;
	}

	public PaymentsId getId() {
		return this.id;
	}

	public void setId(PaymentsId id) {
		this.id = id;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public Customers getCustomers() {
		return this.customers;
	}

	public void setCustomers(Customers customers) {
		this.customers = customers;
	}

	public Date getPaymentdate() {
		return this.paymentdate;
	}

	public void setPaymentdate(Date paymentdate) {
		this.paymentdate = paymentdate;
	}

	public double getAmount() {
		return this.amount;
	}

	public void setAmount(double amount) {
		this.amount = amount;
	}

}
