package com.tpmlogis.bssapp.model;

// Generated 2014. 3. 4 ?? 10:20:32 by Hibernate Tools 4.0.0

/**
 * Products generated by hbm2java
 */
public class Products implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4760748959819940308L;
	private String productcode;
	private Integer version;
	private Productlines productlines;
	private String productname;
	private String productscale;
	private String productvendor;
	private String productdescription;
	private int quantityinstock;
	private double buyprice;
	private double msrp;

	public Products() {
	}

	public Products(String productcode, Productlines productlines, String productname, String productscale, String productvendor,
			String productdescription, int quantityinstock, double buyprice, double msrp) {
		this.productcode = productcode;
		this.productlines = productlines;
		this.productname = productname;
		this.productscale = productscale;
		this.productvendor = productvendor;
		this.productdescription = productdescription;
		this.quantityinstock = quantityinstock;
		this.buyprice = buyprice;
		this.msrp = msrp;
	}

	public String getProductcode() {
		return this.productcode;
	}

	public void setProductcode(String productcode) {
		this.productcode = productcode;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public Productlines getProductlines() {
		return this.productlines;
	}

	public void setProductlines(Productlines productlines) {
		this.productlines = productlines;
	}

	public String getProductname() {
		return this.productname;
	}

	public void setProductname(String productname) {
		this.productname = productname;
	}

	public String getProductscale() {
		return this.productscale;
	}

	public void setProductscale(String productscale) {
		this.productscale = productscale;
	}

	public String getProductvendor() {
		return this.productvendor;
	}

	public void setProductvendor(String productvendor) {
		this.productvendor = productvendor;
	}

	public String getProductdescription() {
		return this.productdescription;
	}

	public void setProductdescription(String productdescription) {
		this.productdescription = productdescription;
	}

	public int getQuantityinstock() {
		return this.quantityinstock;
	}

	public void setQuantityinstock(int quantityinstock) {
		this.quantityinstock = quantityinstock;
	}

	public double getBuyprice() {
		return this.buyprice;
	}

	public void setBuyprice(double buyprice) {
		this.buyprice = buyprice;
	}

	public double getMsrp() {
		return this.msrp;
	}

	public void setMsrp(double msrp) {
		this.msrp = msrp;
	}

}
