package com.tpmlogis.bssapp.model;

// Generated 2014. 3. 4 ?? 10:20:32 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Productlines generated by hbm2java
 */
public class Productlines implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6319459525535599377L;
	private String productline;
	private Integer version;
	private String textdescription;
	private String htmldescription;
	private byte[] image;
	private Set productses = new HashSet(0);

	public Productlines() {
	}

	public Productlines(String productline) {
		this.productline = productline;
	}

	public Productlines(String productline, String textdescription, String htmldescription, byte[] image, Set productses) {
		this.productline = productline;
		this.textdescription = textdescription;
		this.htmldescription = htmldescription;
		this.image = image;
		this.productses = productses;
	}

	public String getProductline() {
		return this.productline;
	}

	public void setProductline(String productline) {
		this.productline = productline;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public String getTextdescription() {
		return this.textdescription;
	}

	public void setTextdescription(String textdescription) {
		this.textdescription = textdescription;
	}

	public String getHtmldescription() {
		return this.htmldescription;
	}

	public void setHtmldescription(String htmldescription) {
		this.htmldescription = htmldescription;
	}

	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

	public Set getProductses() {
		return this.productses;
	}

	public void setProductses(Set productses) {
		this.productses = productses;
	}

}
